apiVersion: apps/v1
kind: Deployment
metadata:
  name: perplexica-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perplexica-backend
  template:
    metadata:
      labels:
        app: perplexica-backend
    spec:
      containers:
      - name: perplexica-backend
        image: perplexica-backend:v1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: SEARXNG_API_URL
          value: "http://searxng:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: perplexica-backend
spec:
  selector:
    app: perplexica-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001

