apiVersion: apps/v1
kind: Deployment
metadata:
  name: perplexica-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perplexica-frontend
  template:
    metadata:
      labels:
        app: perplexica-frontend
    spec:
      containers:
      - name: perplexica-frontend
        image: perplexica-frontend:v1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://127.0.0.1:3001/api"
        - name: NEXT_PUBLIC_WS_URL
          value: "ws://127.0.0.1:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: perplexica-frontend
spec:
  selector:
    app: perplexica-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

